export const UI_STRINGS = {
  editor: {
    title: 'Edit Routine',
    save: 'Save',
    cancel: 'Cancel',
    add: 'Add',
    done: 'Done',
    name: 'Name',
    namePlaceholder: 'Routine Name',
    general: 'General',
    if: {
      title: 'If',
      description: 'Add what will trigger this routine',
      addBtn: 'Add what will trigger this routine',
      conditionLogic: 'Condition Logic',
      allMet: 'All conditions met',
      anyMet: 'Any condition met',
      conditionType: 'Condition Type',
    },
    then: {
      title: 'Then',
      description: 'Add what this routine will do',
      addBtn: 'Add what this routine will do',
      actionType: 'Action Type',
    },
    end: {
      title: 'When routine ends',
      description: 'Choose what happens when this routine stops',
      behaviors: [
        'Return to status before routine started',
        "Don't change anything",
        'Custom (Set action again)',
      ],
      revert: 'Return to status before routine started',
      keep: "Don't change anything",
      custom: 'Custom: Not configured',
      customPrefix: 'Custom: ',
      configureCustom: 'Configure Custom Action',
    },
    errors: {
      emptyName: 'Name is empty',
      noEditor: 'Error: No editor found',
      invalidConfig: 'Invalid configuration',
    },
  },
  triggers: {
    time: 'Time',
    app: 'App Opened',
    wifi: 'Wifi Status',
    bluetooth: 'Bluetooth Status',
    battery: 'Battery Level/Status',
    powerSaver: 'Battery Saver',
    darkMode: 'Dark Mode',
    airplaneMode: 'Airplane Mode',
    headphones: 'Wired Headphones',
    clipboard: 'Clipboard Change',
  },
  actions: {
    openApp: 'Open App',
    wifi: 'Turn Wifi On/Off',
    connectWifi: 'Connect to Wifi',
    bluetooth: 'Turn Bluetooth On/Off',
    connectBluetooth: 'Connect Bluetooth Device',
    disconnectBluetooth: 'Disconnect Bluetooth Device',
    dnd: 'Do Not Disturb',
    airplaneMode: 'Airplane Mode',
    volume: 'Set Volume',
    brightness: 'Set Brightness',
    keyboardBrightness: 'Set Keyboard Brightness',
    wallpaper: 'Set Wallpaper',
    darkMode: 'Dark Mode',
    nightLight: 'Night Light',
    powerSaver: 'Power Saver',
    screenTimeout: 'Screen Timeout',
    screenOrientation: 'Screen Orientation',
    takeScreenshot: 'Take Screenshot',
    notification: 'Send Notification',
    clearClipboard: 'Manage Clipboard',
    openLink: 'Open Link',
  },
  clipboard: {
    operation: 'Operation',
    clear: 'Clear Clipboard',
    none: 'Keep Content',
    sanitize: 'Sanitize URLs',
    sanitizeDescription: 'Automatically remove tracking parameters from URLs.',
    sanitizeConfig: 'Configuration',
    modes: {
      predefined: 'Predefined Params Only',
      merge: 'Predefined + Custom Params',
      custom: 'Custom Params Only',
    },
    customParams: 'Custom Params',
    addParam: 'Add Param',
    noParams: 'No custom params defined',
    paramDomain: 'Domain',
    paramDomainPlaceholder: 'https://instagram.com',
    paramsToRemove: 'Parameters to Remove',
    paramsToRemovePlaceholder: 'igsh, utm_source',
    editParam: 'Edit Param',
    addParamTitle: 'Add Custom Param',
    find: 'Find (Regex)',
    replaceWith: 'Replace With',
  },
};
